Add client-side handling for server-side errors using `errorComponent` and `wrapInSuspense: true`
TanStack/router pull request #1001
Opened 2024-01-15 19:40 UTC by giilbert

Addresses issue #968 fixing error handling during SSR

This pull request adds:
- The ability for server errors to be handled via `errorComponent` while `wrapInSuspense: true`
- Router options `serializeError` and `deserializeError` (with sensible defaults) that allows an end-user to decide what parts of an error to forward from the server to the client
- `/error` pages on the SSR

2024-01-15 19:44 UTC, giilbert commented
This fixes error handling... but only for non-`defer`ed promises. I just noticed that it doesn't fix it for `defer`ed promises. Looking into it now... :sob:

2024-01-16 03:10 UTC, giilbert commented
Error handling in (streaming) SSR seems to work! but the API and documentation need some more work. I'm not 200% sure if I did everything correctly - please give me some feedback, I'm gonna call it a day.

2024-01-16 14:03 UTC, SamiHonkasalo commented
Should the `ResolvedSuspenseBoundary` automatically resolve to a `<Suspense>`, if the route has has a loader and it's being rendered on the server, instead of manually setting `wrapInSuspense: true`?

I tried looking into the way that Remix handles their ErrorBoundary on SSR, but I could not figure it out myself

2024-01-18 21:25 UTC, schiller-manuel requested changes

2024-01-18 21:25 UTC, schiller-manuel commented on examples/react/basic-ssr-streaming-file-based/src/routes/posts/$postId.tsx
> +import { CatchBoundary, FileRoute } from '@tanstack/react-router'
is this import needed?

2024-01-18 21:25 UTC, schiller-manuel commented on packages/react-router/src/Matches.tsx
> +  const error = new Error(serializedData.message)
what happens if `message` or `name` are not part of `serializedData`?

2024-01-18 21:25 UTC, schiller-manuel commented on packages/react-router/src/router.ts
> +  serializeError?: (err: unknown) => Record<string, any>
please document those new properties in docs/api/router/RouterOptionsType.md

2024-01-18 21:53 UTC, schiller-manuel commented on docs/api/router/RouterOptionsType.md
> +#### `deserializeError`
is this not optional?

2024-01-18 22:14 UTC, iDarkLightning commented on docs/api/router/RouterOptionsType.md
> +#### `deserializeError`
oops

2024-01-18 22:15 UTC, schiller-manuel commented
please rebase so that we can merge this

2024-01-19 18:54 UTC, merged