fix(react-router): resolve staticData in createFileRoute
TanStack/router pull request #2074
Opened 2024-08-02 13:02 UTC by honzahruby

Resolves #1978 
`createFileRoute` didn't correctly resolve and enforce `staticData` even when it should. The return type for this function was always compiled down with typescript instead of using the "live" types. During the library build, the `StaticDataRouteOption` was empty, and it resulted in the `staticData` being always optional.

2024-08-02 13:57 UTC, honzahruby commented
Looks like this somehow breaks inferring the router context in `beforeLoad` 😕

2024-08-03 01:49 UTC, SeanCassiere commented
> #1978

Could you clarify? Testing this locally, I can't see the beforeLoad inference breaking. Are you using `createRootRoute` or `createRootRouteWithContext`?

2024-08-03 01:53 UTC, SeanCassiere requested changes
Putting a RC block on this for now till my comment gets resolved.

Testing locally, I couldn't really observe any breakages and it does indeed fix the linked issue.

Once resolved, we can approve and merge this in.

2024-08-03 09:43 UTC, honzahruby commented
@SeanCassiere My bad, I mixed two different versions of the router. This change seems to work fine in the `kitchen-sink-file-based` example, let's move on with it 🚀

2024-08-03 09:46 UTC, SeanCassiere approved these changes
Will check it again and merge in an hour.

2024-08-03 09:55 UTC, merged

2024-08-03 14:17 UTC, schiller-manuel commented
a type test would have been nice, can you add one separately?

2024-08-04 07:38 UTC, honzahruby commented
@schiller-manuel Absolutely, I wanted to add some but there weren’t any even for the basic createRoute. I’ll have a look at it 👍

2024-08-04 10:07 UTC, honzahruby commented
Since `StaticDataRouteOption` is a global interface, it's available to all test files. If we add any required prop to staticData, we'd have to change all existing tests. Any idea how to test this in isolation? 🤔