feat(router-generate): add option to skip generating route manifest
TanStack/router pull request #2100
Opened 2024-08-07 07:46 UTC by honzahruby

Add an option to the generator config to skip generating route manifest, as it's currently only being used in tanstack start. I added it as a non-breaking change so it stays enabled by default.

It's just a comment, but it can grow to thousands of lines of code that need to be processed and removed when we can just not generate it.

2024-08-07 07:56 UTC, SeanCassiere requested changes
@schiller-manuel Since we only use manifest for Start, I'd vote for this going in. Any blockers you see over here?

@honzahruby This'd also have to be updated in the docs, under the `docs/framework/react/guide/file-based-routing.md`.

2024-08-07 07:56 UTC, SeanCassiere commented on packages/router-generator/src/config.ts
> +  generateManifest: z.boolean().optional().default(true),
I believe this should follow the naming above and should be `disableManifestGeneration` or something to that effect.

2024-08-07 23:41 UTC, SeanCassiere approved these changes

2024-08-07 23:58 UTC, merged

2024-08-08 09:18 UTC, honzahruby commented
Thanks a lot @SeanCassiere 🫶