feat(router-plugin): add esbuild plugin
TanStack/router pull request #2578
Opened 2024-10-18 20:13 UTC by benmcginnis

Addresses #2576 by adding an esbuild plugin to the router-plugin package.

Duplicated the basic-file-based e2e test to verify validate the behavior, and replaces the vite config with an esbuild config as well as replacing the vite scripts with esbuild scripts.

tested by running: pnpm run test:e2e from within the e2e/react-router/basic-esbuild-file-based directory.

2024-10-18 20:16 UTC, schiller-manuel commented
please duplicate the e2e project folder (name it `basic-esbuild-file-based`)

2024-10-18 20:45 UTC, schiller-manuel commented on e2e/react-router/basic-esbuild-file-based/src/esbuild.config.js
> +  plugins: [TanStackRouterEsbuild()]
please enable automatic code splitting

2024-10-18 21:17 UTC, SeanCassiere requested changes
Two things of note:

1. In the `examples/react` folder, please create a `quickstart-esbuild-file-based` example. The only difference should be the bundler, the actual source routes should remain the same as rspack, webpack, and vite examples.
2. Update the documentation in `docs/framework/react/guide/file-based-routing.md`, to:
  - Add esbuild into the list of supported bundlers.
  - Add the configuration steps for esbuild, like done for the other bundlers.

2024-10-22 00:03 UTC, SeanCassiere approved these changes
The changes look good.

Now just need to figure out why CI is failing.

2024-10-22 00:21 UTC, merged