fix: allow serverFn errors to also have context
TanStack/router pull request #3037
Opened 2024-12-18 22:42 UTC by tannerlinsley

2024-12-18 22:44 UTC, schiller-manuel commented on packages/start/src/client/createServerFn.ts
> +      console.log('middlewareFn', ctx)
remove

2024-12-18 22:45 UTC, schiller-manuel requested changes
no console logs please

2024-12-18 22:47 UTC, schiller-manuel commented on packages/start/src/client/createServerFn.ts
> +          console.log('newCtx', newCtx)
remove here as well

2024-12-19 21:50 UTC, tannerlinsley commented
Logs gone.

2024-12-23 06:25 UTC, merged