Solid router adapter
TanStack/router pull request #516
Opened 2023-02-03 23:00 UTC by Tanner-Scadden

Base types conversions. Began work on the router/match context. Rough outline of useStore conversion.

2023-02-05 05:18 UTC, tannerlinsley requested changes

2023-02-05 05:18 UTC, tannerlinsley commented on packages/solid-loaders/src/index.tsx
> +type StrictLoaderInstance_<TLoaderInstance> =
Decided to switch this in the core so `data` is always defined, but then in the adapter, we now have `NullableLoaderInstance_` which references the core `NullableLoaderInstance`.

2023-02-05 05:18 UTC, tannerlinsley commented on packages/solid-loaders/src/index.tsx
> +  : StrictLoaderInstance_<TResolvedLoaderInstance> {
This condition need to be swapped for the change to `NullableLoaderInstance` instead of strict

2023-02-05 05:18 UTC, tannerlinsley commented on packages/solid-router/src/index.tsx
> +                color: 'red',
This markup/style has changed on the react-router package

2023-02-05 05:26 UTC, tannerlinsley requested changes

2023-02-05 05:26 UTC, tannerlinsley commented on packages/solid-store/src/index.tsx
> +  )
This will likely need to turn into a solid store and uses solid-store's reconcile to make it granularly reactive.

2023-02-06 22:25 UTC, Tanner-Scadden commented
Note on the store adapter. When I added reconcile in it wasn't rendering anything. Not sure why, but that would be a huge performance gain.

2023-02-08 05:17 UTC, merged